"""<br>
    @Author: Prayag Bhoir<br>
    @Date: 5-08-2024 <br>
    @Last Modified by: Prayag Bhoir<br>
    @Last Modified time: 5-08-2024 <br>
    @Title : Python programs on numpy<br>
"""

In [1]:
import numpy as np

## 1. Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array.<br>
Expected Output:
Original List: [12.23, 13.32, 100, 36.32]<br>
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]

In [2]:

def main():

  lst=[1,2,3,4]
  print(lst,type(lst))

  np_array = np.array(lst, np.int8)
  print(np_array,type(np_array))

if __name__=="__main__":
  main()


[1, 2, 3, 4] <class 'list'>
[1 2 3 4] <class 'numpy.ndarray'>


## 2. Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:<br>
[[ 2 3 4]<br>
[ 5 6 7]<br>
[ 8 9 10]]

In [21]:

def main():
	matrix = np.arange(2,11).reshape(3,3)
	print("The 3x3 matrix ranging from 2-10 :\n",matrix)

if __name__=="__main__":
  	main()

The 3x3 matrix ranging from 2-10 :
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
