"""<br>
    @Author: Prayag Bhoir<br>
    @Date: 5-08-2024 <br>
    @Last Modified by: Prayag Bhoir<br>
    @Last Modified time: 5-08-2024 <br>
    @Title : Python programs on numpy<br>
"""

In [29]:
import numpy as np

## 1. Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array.<br>
Expected Output:
Original List: [12.23, 13.32, 100, 36.32]<br>
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]

In [30]:

def main():

  lst=[1,2,3,4]
  print(lst,type(lst))

  np_array = np.array(lst, np.int8)
  print(np_array,type(np_array))

if __name__=="__main__":
  main()


[1, 2, 3, 4] <class 'list'>
[1 2 3 4] <class 'numpy.ndarray'>


## 2. Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:<br>
[[ 2 3 4]<br>
[ 5 6 7]<br>
[ 8 9 10]]

In [31]:

def main():
	matrix = np.arange(2,11).reshape(3,3)
	print("The 3x3 matrix ranging from 2-10 :\n",matrix)

if __name__=="__main__":
  	main()

The 3x3 matrix ranging from 2-10 :
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


## 3. Write a Python program to create a null vector of size 10 and update sixth value to 11.  
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]  <br>
Update sixth value to 11  <br>
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.] 

In [32]:
def main():
	matrix = np.zeros(10,dtype=int)
	matrix[6-1]=11
	print(matrix)
	

if __name__=="__main__":
  	main()

[ 0  0  0  0  0 11  0  0  0  0]


	
## 4. Write a Python program to reverse an array (first element becomes last).
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]<br>
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [33]:
def reverse_array(arr):
	"""
    Description:
      This function reverse the given array
    Parameters:
      arr(array): Array of items/int

    Returns:
      array : Reverse the array 
    """	
	return np.flip(arr)

def main():
	arr = np.arange(11)
	print(f"Original Array: {arr}")
	print(f"Reverse array: {reverse_array(arr)}")
	

if __name__=="__main__":
  	main()

Original Array: [ 0  1  2  3  4  5  6  7  8  9 10]
Reverse array: [10  9  8  7  6  5  4  3  2  1  0]


## 5. Write a Python program to create a 2d array with 1 on the border and 0 inside.


Expected Output:
<br>
Original array:<br>
[[ 1. 1. 1. 1. 1.]<br>
[ 1. 1. 1. 1. 1.]<br>
[ 1. 1. 1. 1. 1.]<br>
[ 1. 1. 1. 1. 1.]<br>
[ 1. 1. 1. 1. 1.]]<br><br>
1 on the border and 0 inside in the array<br>
[[ 1. 1. 1. 1. 1.]<br>
[ 1. 0. 0. 0. 1.]<br>
[ 1. 0. 0. 0. 1.]<br>
[ 1. 0. 0. 0. 1.]<br>
[ 1. 1. 1. 1. 1.]]

In [34]:
def main():
	arr = np.ones((5,5))
	print("Original array : \n",arr)
	arr[1:-1,1:-1]=0
	print("\nModified array : \n",arr)
	

if __name__=="__main__":
  	main()

Original array : 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Modified array : 
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## 6. Write a Python program to add a border (filled with 0's) around an existing array.  
Expected Output: <br>
Original array:  <br>
[[ 1. 1. 1.]  <br>
[ 1. 1. 1.]  <br>
[ 1. 1. 1.]]  <br>
1 on the border and 0 inside in the array  <br><br>
[[ 0. 0. 0. 0. 0.]  <br>
[ 0. 1. 1. 1. 0.]  <br>
[ 0. 1. 1. 1. 0.]  <br>
[ 0. 1. 1. 1. 0.]  <br>
[ 0. 0. 0. 0. 0.]]

In [35]:
def main():
	arr = np.ones((3,3))
	print("Original array : \n",arr)
	arr = np.pad(arr,pad_width=1,mode='constant',constant_values=0)
	print("\nModified array : \n",arr)
	

if __name__=="__main__":
  	main()

Original array : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Modified array : 
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


## 7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.  
Checkerboard pattern: <br>
[[0 1 0 1 0 1 0 1]  <br>
[1 0 1 0 1 0 1 0]  <br>
[0 1 0 1 0 1 0 1]  <br>
[1 0 1 0 1 0 1 0]  <br>
[0 1 0 1 0 1 0 1]  <br>
[1 0 1 0 1 0 1 0]  <br>
[0 1 0 1 0 1 0 1]  <br>
[1 0 1 0 1 0 1 0]]

In [36]:
def main():
	matrix = np.zeros((8,8), dtype=int)
	matrix[::2, ::2] = 1  # Set the elements at even indices to 1
	matrix[1::2, 1::2] = 1  # Set the elements at odd indices to 1
	print(matrix)

if __name__=="__main__":
  main()

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


## 8. Write a Python program to convert a list and tuple into arrays.  
List to array: <br>
[1 2 3 4 5 6 7 8]  <br><br>
Tuple to array: <br>
[[8 4 6]  <br>
[1 2 3]]

In [37]:
def main():
	lst = [1, 2, 3, 4, 5, 6, 7, 8]
	tpl = ((8, 4, 6), (1, 2, 3))

	print("List to array:")
	print(np.array(lst))

	print("\nTuple to array:")
	print(np.array(tpl))
    
if __name__=="__main__":
  main()

List to array:
[1 2 3 4 5 6 7 8]

Tuple to array:
[[8 4 6]
 [1 2 3]]


## 9. Write a Python program to append values to the end of an array.  
Expected Output: <br>
Original array:<br> 
[10, 20, 30]  

In [38]:
def append_to_array(array, values):
  """
	Description:
    Append values to the end of a NumPy array.
    
  Parameters:
      array (np.ndarray): The original NumPy array.
      values (list or np.ndarray): Values to be appended.
    
  Returns:
      np.ndarray(array): The updated NumPy array with appended values.
    """
  return np.append(array, values)

def main():
  original_array = np.array([10, 20, 30])
  values_to_append = [40, 50, 60]

  updated_array = append_to_array(original_array, values_to_append)
    
  print("Original array:")
  print(original_array)
    
  print("\nArray after appending values:")
  print(updated_array)

if __name__ == "__main__":
  main()

Original array:
[10 20 30]

Array after appending values:
[10 20 30 40 50 60]


## 10. Write a Python program to find the real and imaginary parts of an array of complex numbers.  
Expected Output: <br>
Original array [ 1.00000000+0.j 0.70710678+0.70710678j] <br> <br>
Real part of the array:  <br>
[ 1. 0.70710678]  <br><br>
Imaginary part of the array: <br>
[ 0. 0.70710678]  

In [39]:
def main():
	complex_array = np.array([1 + 9j, 2 + 7j])
	print(f"Complex numbers: {complex_array}")
	print(f"Real : {np.real(complex_array)} Imaginary: {np.imag(complex_array)}")

if __name__=="__main__":
  main()

Complex numbers: [1.+9.j 2.+7.j]
Real : [1. 2.] Imaginary: [9. 7.]


## 11. Write a Python program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.  
Expected Output: <br>
Size of the array: 3 <br>
Length of one array element in bytes: 8 <br> 
Total bytes consumed by the elements of the array: 24  

In [40]:
def main():
	array = np.array([1, 2, 3])
	print(f"size of array: {array.size}")
	print(f"Length of one element in  byts: {array.itemsize}")
	print(f"Total byts of array: {array.itemsize*array.size}")

if __name__=="__main__":
  main()

size of array: 3
Length of one element in  byts: 8
Total byts of array: 24


## 12. Write a Python program to find common values between two arrays.  
Expected Output: <br>
Array1: [ 0 10 20 40 60] <br> 
Array2: [10, 30, 40] <br>
Common values between two arrays: <br>
[10 40]  

In [41]:
def find_common_values(array1, array2):
  """
	Description:
    this function find common values between two NumPy arrays.
    
  Parameters:
    array1 (np.ndarray): The first array.
    array2 (np.ndarray): The second array.
    
  Returns:
    np.ndarray: An array of common values between the two input arrays.
    """
  return np.intersect1d(array1, array2)

def main():
    array1 = np.array([0, 10, 20, 40, 60])
    array2 = np.array([10, 30, 40])
    
    common_values = find_common_values(array1, array2)
    
    print(f"Array1: {array1}")
    print(f"Array2: {array2}")
    print(f"Common values between two arrays: {common_values}")

if __name__ == "__main__":
    main()


Array1: [ 0 10 20 40 60]
Array2: [10 30 40]
Common values between two arrays: [10 40]


## 13. Write a Python program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.  
Expected Output:<br> 
Array1: [ 0 10 20 40 60 80] <br> 
Array2: [10, 30, 40, 50, 70, 90]  <br> 
Set difference between two arrays: <br> 
[ 0 20 60 80] 

In [42]:
def find_set_difference(array1, array2):
  """
	Description:
    Find the set difference of two NumPy arrays.
    
  Parameters:
    array1 (array): The first array.
    array2 (array): The second array.
    
  Returns:
    array: An array of values in array1 that are not in array2.
    """
  return np.setdiff1d(array1, array2)

def main():
  array1 = np.array([0, 10, 20, 40, 60, 80])
  array2 = np.array([10, 30, 40, 50, 70, 90])
  
  set_difference = find_set_difference(array1, array2)
   
  print(f"Array1: {array1}")
  print(f"Array2: {array2}")
  print(f"Set difference between two arrays: {set_difference}")

if __name__ == "__main__":
  main()


Array1: [ 0 10 20 40 60 80]
Array2: [10 30 40 50 70 90]
Set difference between two arrays: [ 0 20 60 80]


## 14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays.  
Array1: [ 0 10 20 40 60 80]  <br>
Array2: [10, 30, 40, 50, 70] <br> 
Unique values that are in only one (not both) of the input arrays: <br> 
[ 0 20 30 50 60 70 80] 


In [43]:

def find_set_exclusive_or(array1, array2):
  """
	Description:
  	Find the set exclusive-or (symmetric difference) of two NumPy arrays.
  
  Parameters:
  	array1 (array): The first array.
  	array2 (array): The second array.
  
  Returns:
  	array: An array of unique values that are in only one of the input arrays.
  """
  return np.setxor1d(array1, array2)

def main():
  array1 = np.array([0, 10, 20, 40, 60, 80])
  array2 = np.array([10, 30, 40, 50, 70])
  
  exclusive_or = find_set_exclusive_or(array1, array2)
  
  print(f"Array1: {array1}")
  print(f"Array2: {array2}")
  print(f"Unique values that are in only one (not both) of the input arrays: {exclusive_or}")

if __name__ == "__main__":
  main()


Array1: [ 0 10 20 40 60 80]
Array2: [10 30 40 50 70]
Unique values that are in only one (not both) of the input arrays: [ 0 20 30 50 60 70 80]


## 15. Write a Python program compare two arrays using numpy.  
Array a: [1 2] <br>
Array b: [4 5] <br>
a > b  <br>
[False False] <br>
a >= b  <br>
[False False]  <br>
a < b  <br>
[ True True]  <br>
a <= b  <br>
[ True True]<br>

In [44]:

def compare_arrays(a, b):
  """
	Description:
  	Compare two NumPy arrays.
  
  Parameters:
  	a (array): The first array.
  	b (array): The second array.
  
  Returns:
  	dict: A dictionary containing the results of comparisons.
  """
  return {
    'a > b': a > b,
    'a >= b': a >= b,
    'a < b': a < b,
    'a <= b': a <= b
  }

def main():

  array1 = np.array([1, 6])
  array2= np.array([4, 5])
  
  results = compare_arrays(array1,array2)
  
  for comparison, result in results.items():
    print(f"{comparison} \n{result}")

if __name__ == "__main__":
  main()


a > b 
[False  True]
a >= b 
[False  True]
a < b 
[ True False]
a <= b 
[ True False]


## 16. Write a Python program to save a NumPy array to a text file.  

In [45]:
def main():
	array = np.array([1,2,3,4])
	np.savetxt("file.txt",array)
if __name__ == "__main__":
  main()


## 17. Write a Python program to create a contiguous flattened array.  
Original array: <br>
[[10 20 30]  <br>
[20 40 50]]  <br>
New flattened array: <br> 
[10 20 30 20 40 50] 

In [46]:
def main():
	array = np.array([[1,2,3,4],[1,2,3,4]])
	print("Original arary: \n",array)
	new_array = array.ravel()
	print("Flattened array :",new_array)
if __name__ == "__main__":
  main()
	
	

Original arary: 
 [[1 2 3 4]
 [1 2 3 4]]
Flattened array : [1 2 3 4 1 2 3 4]


## 18.Write a Python program to change the data type of an array.  
Expected Output: <br>
[[ 2 4 6] <br>
[ 6 8 10]]  <br><br>
Data type of the array x is: int32 <br> 
New Type: float64  <br>
[[ 2. 4. 6.]  <br>
[ 6. 8. 10.]]

In [47]:
def main():
	array = np.array([[1,2,3,4],[1,2,3,4]])
	print("Original arary: \n", array, array.dtype )
	new_array = array.astype('float64')
	print("Flattened array :\n", new_array, new_array.dtype)
if __name__ == "__main__":
  main()
  
	

Original arary: 
 [[1 2 3 4]
 [1 2 3 4]] int64
Flattened array :
 [[1. 2. 3. 4.]
 [1. 2. 3. 4.]] float64


## 19.Write a Python program to create a 3-D array with ones on a diagonal and zeros elsewhere.  
Expected Output: <br>
[[ 1. 0. 0.] <br>
[ 0. 1. 0.]  <br>
[ 0. 0. 1.]] <br>

In [48]:
def main():
	print(np.identity(3))
     
	#print(np.diagflat(np.array([1,1,1])))
if __name__ == "__main__":
  main()
  

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 20.Write a Python program to create an array which looks like below array.  
Expected Output: <br>
[[ 0. 0. 0.] <br>
[ 1. 0. 0.] <br>
[ 1. 1. 0.] <br>
[ 1. 1. 1.]] 

In [49]:
def main():
	array = np.ones((4,3))
	print("Original arary: \n", array)
	new_array = np.triu(array)
	new_array = np.fliplr(new_array)
	new_array = np.flipud(new_array)
	print("Flattened array :\n", new_array)
if __name__ == "__main__":
  main()
  

Original arary: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Flattened array :
 [[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


## 21.Write a Python program to concatenate two 2-dimensional arrays.  
Expected Output: <br>
Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]] )<br>
Expected Output: <br>
[[ 0 1 3 0 2 4] <br>
[ 5 7 9 6 8 10]]  

In [50]:
def main():
	array1 = np.array([[1,2],[3,4]])
	array2 = np.array([[1,2],[3,4]])
	new_array = np.concatenate((array1,array2),axis=1)
	print("Flattened array :\n", new_array)
     
if __name__ == "__main__":
  main()
  

Flattened array :
 [[1 2 1 2]
 [3 4 3 4]]


## 22. Write a Python program to make an array immutable (read-only).  
Expected Output: <br>
Test the array is read-only or not:  <br>
Try to change the value of the first element:  <br>
Traceback (most recent call last):  <br>
File "19236bd0-0bd9-11e7-a232-c706d0968eb6.py", line 6, in  <br> 
x[0] = 1  <br>
ValueError: assignment destination is read-only 

In [51]:
def main():
	array = np.array([[1,2],[3,4]])
	array.flags.writeable=False
	array[0]=[0,0]   
     
if __name__ == "__main__":
  main()
  

ValueError: assignment destination is read-only

## 23. Write a Python program to create an array of (3, 4) shape, multiply every elementvalue by 3 and display the new array. 
Expected Output: <br>
Original array elements: <br>
[[ 0 1 2 3] <br>
[ 4 5 6 7] <br>
[ 8 9 10 11]] <br> <br>
New array elements: <br>
[[ 0 3 6 9] <br>
[12 15 18 21] <br>
[24 27 30 33]]


In [ ]:
def main():
	array = np.arange(12).reshape(3,4)

	
	print("Original array :\n",array)
	print("After multiplecation by 3 :\n",array*3)
	
     
if __name__ == "__main__":
  main()
  

Original array :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
After multiplecation by 3 :
 [[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


## 24. Write a Python program to convert a NumPy array into Python list structure.
Expected Output: <br>
Original array elements: <br>
[[0 1] <br>
[2 3] <br>
[4 5]] <br> <br>
Array to list: <br>
[[0, 1], [2, 3], [4, 5]] <br>

In [ ]:
def main():
	array = np.arange(6).reshape(3,2)
	new_array = array.tolist()
	
	print("Original array :\n",array)
	print("After multiplecation by 3 :\n",new_array)
	
     
if __name__ == "__main__":
  main()
  

Original array :
 [[0 1]
 [2 3]
 [4 5]]
After multiplecation by 3 :
 [[0, 1], [2, 3], [4, 5]]


## 25. Write a Python program to convert a NumPy array into Python list structure.
Expected Output: <br>
Original array elements: <br>
[ 0.26153123 0.52760141 0.5718299 0.5927067 0.7831874 0.69746349 <br>
0.35399976 0.99469633 0.0694458 0.54711478] <br> <br>
Print array values with precision 3: <br>
[ 0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]

In [59]:
def main():
	array = np.array([ 0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349, 0.35399976, 0.99469633,0.0694458, 0.54711478])
	print("Original array :\n",array)
	np.set_printoptions(precision=3)
	print("After multiplecation by 3 :\n",array)
	   
if __name__ == "__main__":
  main()
  

Original array :
 [0.26153123 0.52760141 0.5718299  0.5927067  0.7831874  0.69746349
 0.35399976 0.99469633 0.0694458  0.54711478]
After multiplecation by 3 :
 [0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]


## 26. Write a Python program to suppresses the use of scientific notation for small numbers in numpy array. 
Expected Output: <br>
Original array elements: <br>
[ 1.60000000e-10 1.60000000e+00 1.20000000e+03 2.35000000e-01] <br> <br>
Print array values with precision 3: <br>
[ 0. 1.6 1200. 0.235]

In [63]:
def main():
	array = np.array([ 1.60000000e-10 ,1.60000000e+00, 1.20000000e+03, 2.35000000e-01])
	print("Original array :\n",array)
	np.set_printoptions(precision=3,suppress=True)
	print("After multiplecation by 3 :\n",array)
	   
if __name__ == "__main__":
  main()
  

Original array :
 [1.60e-10 1.60e+00 1.20e+03 2.35e-01]
After multiplecation by 3 :
 [   0.       1.6   1200.       0.235]


## 27. Write a Python program to how to add an extra column to an numpy array.
Expected Output: <br>
[[ 10 20 30 100] <br>
[ 40 50 60 200]]

In [79]:
def main():
	array = np.array([[10,20,30],[40,50,60]])
	print("Original array :\n", array)
  
	new_array = np.hstack((array,[[100],[200]] ))
	print("Added column  :\n", new_array)
     
if __name__ == "__main__":
  main()
  

Original array :
 [[10 20 30]
 [40 50 60]]
Added column  :
 [[ 10  20  30 100]
 [ 40  50  60 200]]


## 28. Write a Python program to remove specific elements in a numpy array.
Expected Output:<br>
Original array:<br>
[ 10 20 30 40 50 60 70 80 90 100]<br><br>
Delete first, fourth and fifth elements:<br>
[ 20 30 60 70 80 90 100]


In [84]:
def main():
	array = np.arange(10,110,10)
	print("Original array :\n", array)
  
	new_array = np.delete(array,[0,3,4])
	print("Added column  :\n", new_array)
     
if __name__ == "__main__":
  main()
  

Original array :
 [ 10  20  30  40  50  60  70  80  90 100]
Added column  :
 [ 20  30  60  70  80  90 100]
