"""<br>
    @Author: Prayag Bhoir<br>
    @Date: 5-08-2024 <br>
    @Last Modified by: Prayag Bhoir<br>
    @Last Modified time: 5-08-2024 <br>
    @Title : Python programs on numpy<br>
"""

In [2]:
import numpy as np

## 1. Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array.<br>
Expected Output:
Original List: [12.23, 13.32, 100, 36.32]<br>
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]

In [3]:

def main():

  lst=[1,2,3,4]
  print(lst,type(lst))

  np_array = np.array(lst, np.int8)
  print(np_array,type(np_array))

if __name__=="__main__":
  main()


[1, 2, 3, 4] <class 'list'>
[1 2 3 4] <class 'numpy.ndarray'>


## 2. Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:<br>
[[ 2 3 4]<br>
[ 5 6 7]<br>
[ 8 9 10]]

In [4]:

def main():
	matrix = np.arange(2,11).reshape(3,3)
	print("The 3x3 matrix ranging from 2-10 :\n",matrix)

if __name__=="__main__":
  	main()

The 3x3 matrix ranging from 2-10 :
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


## 3. Write a Python program to create a null vector of size 10 and update sixth value to 11.  
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]  <br>
Update sixth value to 11  <br>
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.] 

In [5]:
def main():
	matrix = np.zeros(10,dtype=int)
	matrix[6-1]=11
	print(matrix)
	

if __name__=="__main__":
  	main()

[ 0  0  0  0  0 11  0  0  0  0]


	
## 4. Write a Python program to reverse an array (first element becomes last).
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]<br>
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [27]:
def reverse_array(arr):
	"""
    Description:
      This function reverse the given array
    Parameters:
      arr(array): Array of items/int

    Returns:
      array : Reverse the array 
    """	
	return np.flip(arr)

def main():
	arr = np.arange(11)
	print(f"Original Array: {arr}")
	print(f"Reverse array: {reverse_array(arr)}")
	

if __name__=="__main__":
  	main()

Original Array: [ 0  1  2  3  4  5  6  7  8  9 10]
Reverse array: [10  9  8  7  6  5  4  3  2  1  0]


## 5. Write a Python program to create a 2d array with 1 on the border and 0 inside.


Expected Output:
<br>
Original array:<br>
[[ 1. 1. 1. 1. 1.]<br>
[ 1. 1. 1. 1. 1.]<br>
[ 1. 1. 1. 1. 1.]<br>
[ 1. 1. 1. 1. 1.]<br>
[ 1. 1. 1. 1. 1.]]<br><br>
1 on the border and 0 inside in the array<br>
[[ 1. 1. 1. 1. 1.]<br>
[ 1. 0. 0. 0. 1.]<br>
[ 1. 0. 0. 0. 1.]<br>
[ 1. 0. 0. 0. 1.]<br>
[ 1. 1. 1. 1. 1.]]

In [7]:
def main():
	arr = np.ones((5,5))
	print("Original array : \n",arr)
	arr[1:-1,1:-1]=0
	print("\nModified array : \n",arr)
	

if __name__=="__main__":
  	main()

Original array : 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Modified array : 
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## 6. Write a Python program to add a border (filled with 0's) around an existing array.  
Expected Output: <br>
Original array:  <br>
[[ 1. 1. 1.]  <br>
[ 1. 1. 1.]  <br>
[ 1. 1. 1.]]  <br>
1 on the border and 0 inside in the array  <br><br>
[[ 0. 0. 0. 0. 0.]  <br>
[ 0. 1. 1. 1. 0.]  <br>
[ 0. 1. 1. 1. 0.]  <br>
[ 0. 1. 1. 1. 0.]  <br>
[ 0. 0. 0. 0. 0.]]

In [8]:
def main():
	arr = np.ones((3,3))
	print("Original array : \n",arr)
	arr = np.pad(arr,pad_width=1,mode='constant',constant_values=0)
	print("\nModified array : \n",arr)
	

if __name__=="__main__":
  	main()

Original array : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Modified array : 
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


## 7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.  
Checkerboard pattern: <br>
[[0 1 0 1 0 1 0 1]  <br>
[1 0 1 0 1 0 1 0]  <br>
[0 1 0 1 0 1 0 1]  <br>
[1 0 1 0 1 0 1 0]  <br>
[0 1 0 1 0 1 0 1]  <br>
[1 0 1 0 1 0 1 0]  <br>
[0 1 0 1 0 1 0 1]  <br>
[1 0 1 0 1 0 1 0]]

In [9]:
def main():
	matrix = np.zeros((8,8), dtype=int)
	matrix[::2, ::2] = 1  # Set the elements at even indices to 1
	matrix[1::2, 1::2] = 1  # Set the elements at odd indices to 1
	print(matrix)

if __name__=="__main__":
  main()

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


## 8. Write a Python program to convert a list and tuple into arrays.  
List to array: <br>
[1 2 3 4 5 6 7 8]  <br><br>
Tuple to array: <br>
[[8 4 6]  <br>
[1 2 3]]

In [29]:
def main():
	lst = [1, 2, 3, 4, 5, 6, 7, 8]
	tpl = ((8, 4, 6), (1, 2, 3))

	print("List to array:")
	print(np.array(lst))

	print("\nTuple to array:")
	print(np.array(tpl))
    
if __name__=="__main__":
  main()

List to array:
[1 2 3 4 5 6 7 8]

Tuple to array:
[[8 4 6]
 [1 2 3]] [0. 0. 0.]


## 9. Write a Python program to append values to the end of an array.  
Expected Output: <br>
Original array:<br> 
[10, 20, 30]  

In [11]:
def append_to_array(array, values):
  """
	Description:
    Append values to the end of a NumPy array.
    
  Parameters:
      array (np.ndarray): The original NumPy array.
      values (list or np.ndarray): Values to be appended.
    
  Returns:
      np.ndarray(array): The updated NumPy array with appended values.
    """
  return np.append(array, values)

def main():
  original_array = np.array([10, 20, 30])
  values_to_append = [40, 50, 60]

  updated_array = append_to_array(original_array, values_to_append)
    
  print("Original array:")
  print(original_array)
    
  print("\nArray after appending values:")
  print(updated_array)

if __name__ == "__main__":
  main()

Original array:
[10 20 30]

Array after appending values:
[10 20 30 40 50 60]


## 10. Write a Python program to find the real and imaginary parts of an array of complex numbers.  
Expected Output: <br>
Original array [ 1.00000000+0.j 0.70710678+0.70710678j] <br> <br>
Real part of the array:  <br>
[ 1. 0.70710678]  <br><br>
Imaginary part of the array: <br>
[ 0. 0.70710678]  

In [12]:
def main():
	complex_array = np.array([1 + 9j, 2 + 7j])
	print(f"Complex numbers: {complex_array}")
	print(f"Real : {np.real(complex_array)} Imaginary: {np.imag(complex_array)}")

if __name__=="__main__":
  main()

Complex numbers: [1.+9.j 2.+7.j]
Real : [1. 2.] Imaginary: [9. 7.]


## 11. Write a Python program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.  
Expected Output: <br>
Size of the array: 3 <br>
Length of one array element in bytes: 8 <br> 
Total bytes consumed by the elements of the array: 24  

In [13]:
def main():
	array = np.array([1, 2, 3])
	print(f"size of array: {array.size}")
	print(f"Length of one element in  byts: {array.itemsize}")
	print(f"Total byts of array: {array.itemsize*array.size}")

if __name__=="__main__":
  main()

size of array: 3
Length of one element in  byts: 8
Total byts of array: 24


## 12. Write a Python program to find common values between two arrays.  
Expected Output: <br>
Array1: [ 0 10 20 40 60] <br> 
Array2: [10, 30, 40] <br>
Common values between two arrays: <br>
[10 40]  

In [14]:
def find_common_values(array1, array2):
  """
	Description:
    this function find common values between two NumPy arrays.
    
  Parameters:
    array1 (np.ndarray): The first array.
    array2 (np.ndarray): The second array.
    
  Returns:
    np.ndarray: An array of common values between the two input arrays.
    """
  return np.intersect1d(array1, array2)

def main():
    array1 = np.array([0, 10, 20, 40, 60])
    array2 = np.array([10, 30, 40])
    
    common_values = find_common_values(array1, array2)
    
    print(f"Array1: {array1}")
    print(f"Array2: {array2}")
    print(f"Common values between two arrays: {common_values}")

if __name__ == "__main__":
    main()


Array1: [ 0 10 20 40 60]
Array2: [10 30 40]
Common values between two arrays: [10 40]


## 13. Write a Python program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.  
Expected Output:<br> 
Array1: [ 0 10 20 40 60 80] <br> 
Array2: [10, 30, 40, 50, 70, 90]  <br> 
Set difference between two arrays: <br> 
[ 0 20 60 80] 

In [15]:
def find_set_difference(array1, array2):
  """
	Description:
    Find the set difference of two NumPy arrays.
    
  Parameters:
    array1 (array): The first array.
    array2 (array): The second array.
    
  Returns:
    array: An array of values in array1 that are not in array2.
    """
  return np.setdiff1d(array1, array2)

def main():
  array1 = np.array([0, 10, 20, 40, 60, 80])
  array2 = np.array([10, 30, 40, 50, 70, 90])
  
  set_difference = find_set_difference(array1, array2)
   
  print(f"Array1: {array1}")
  print(f"Array2: {array2}")
  print(f"Set difference between two arrays: {set_difference}")

if __name__ == "__main__":
  main()


Array1: [ 0 10 20 40 60 80]
Array2: [10 30 40 50 70 90]
Set difference between two arrays: [ 0 20 60 80]


## 14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays.  
Array1: [ 0 10 20 40 60 80]  <br>
Array2: [10, 30, 40, 50, 70] <br> 
Unique values that are in only one (not both) of the input arrays: <br> 
[ 0 20 30 50 60 70 80] 


In [16]:

def find_set_exclusive_or(array1, array2):
  """
	Description:
  	Find the set exclusive-or (symmetric difference) of two NumPy arrays.
  
  Parameters:
  	array1 (array): The first array.
  	array2 (array): The second array.
  
  Returns:
  	array: An array of unique values that are in only one of the input arrays.
  """
  return np.setxor1d(array1, array2)

def main():
  array1 = np.array([0, 10, 20, 40, 60, 80])
  array2 = np.array([10, 30, 40, 50, 70])
  
  exclusive_or = find_set_exclusive_or(array1, array2)
  
  print(f"Array1: {array1}")
  print(f"Array2: {array2}")
  print(f"Unique values that are in only one (not both) of the input arrays: {exclusive_or}")

if __name__ == "__main__":
  main()


Array1: [ 0 10 20 40 60 80]
Array2: [10 30 40 50 70]
Unique values that are in only one (not both) of the input arrays: [ 0 20 30 50 60 70 80]


## 15. Write a Python program compare two arrays using numpy.  
Array a: [1 2] <br>
Array b: [4 5] <br>
a > b  <br>
[False False] <br>
a >= b  <br>
[False False]  <br>
a < b  <br>
[ True True]  <br>
a <= b  <br>
[ True True]<br>

In [17]:

def compare_arrays(a, b):
  """
	Description:
  	Compare two NumPy arrays.
  
  Parameters:
  	a (array): The first array.
  	b (array): The second array.
  
  Returns:
  	dict: A dictionary containing the results of comparisons.
  """
  return {
    'a > b': a > b,
    'a >= b': a >= b,
    'a < b': a < b,
    'a <= b': a <= b
  }

def main():

  array1 = np.array([1, 6])
  array2= np.array([4, 5])
  
  results = compare_arrays(array1,array2)
  
  for comparison, result in results.items():
    print(f"{comparison} \n{result}")

if __name__ == "__main__":
  main()


a > b 
[False  True]
a >= b 
[False  True]
a < b 
[ True False]
a <= b 
[ True False]


## 16. Write a Python program to save a NumPy array to a text file.  

In [18]:
def main():
	array = np.array([1,2,3,4])
	np.savetxt("file.txt",array)
if __name__ == "__main__":
  main()
