"""<br>
    @Author: Prayag Bhoir<br>
    @Date: 5-08-2024 <br>
    @Last Modified by: Prayag Bhoir<br>
    @Last Modified time: 5-08-2024 <br>
    @Title : Python programs on numpy<br>
"""

In [14]:
import numpy as np

## 1. Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array.<br>
Expected Output:
Original List: [12.23, 13.32, 100, 36.32]<br>
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]

In [15]:

def main():

  lst=[1,2,3,4]
  print(lst,type(lst))

  np_array = np.array(lst, np.int8)
  print(np_array,type(np_array))

if __name__=="__main__":
  main()


[1, 2, 3, 4] <class 'list'>
[1 2 3 4] <class 'numpy.ndarray'>


## 2. Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:<br>
[[ 2 3 4]<br>
[ 5 6 7]<br>
[ 8 9 10]]

In [16]:

def main():
	matrix = np.arange(2,11).reshape(3,3)
	print("The 3x3 matrix ranging from 2-10 :\n",matrix)

if __name__=="__main__":
  	main()

The 3x3 matrix ranging from 2-10 :
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


## 3. Write a Python program to create a null vector of size 10 and update sixth value to 11.  
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]  <br>
Update sixth value to 11  <br>
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.] 

In [17]:
def main():
	matrix = np.zeros(10,dtype=int)
	matrix[6-1]=11
	print(matrix)
	

if __name__=="__main__":
  	main()

[ 0  0  0  0  0 11  0  0  0  0]


	
## 4. Write a Python program to reverse an array (first element becomes last).
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]<br>
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [30]:
def reverse_array(arr):
	"""
    Description:
      This function reverse the given array
    Parameters:
      arr(array): Array of items/int

    Returns:
      array : Reverse the array 
    """	
	return np.flip(arr)

def main():
	arr = np.arange(11)
	print(f"Original Array: {arr}")
	print(f"Reverse array: {reverse_array(arr)}")
	

if __name__=="__main__":
  	main()

Original Array: [ 0  1  2  3  4  5  6  7  8  9 10]
Reverse array: [10  9  8  7  6  5  4  3  2  1  0]
