"""<br>
    @Author: Prayag Bhoir<br>
    @Date: 5-08-2024 <br>
    @Last Modified by: Prayag Bhoir<br>
    @Last Modified time: 5-08-2024 <br>
    @Title : Python programs on numpy<br>
"""

In [2]:
import numpy as np

## 1. Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array.<br>
Expected Output:
Original List: [12.23, 13.32, 100, 36.32]<br>
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]

In [3]:

def main():

  lst=[1,2,3,4]
  print(lst,type(lst))

  np_array = np.array(lst, np.int8)
  print(np_array,type(np_array))

if __name__=="__main__":
  main()


[1, 2, 3, 4] <class 'list'>
[1 2 3 4] <class 'numpy.ndarray'>


## 2. Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:<br>
[[ 2 3 4]<br>
[ 5 6 7]<br>
[ 8 9 10]]

In [4]:

def main():
	matrix = np.arange(2,11).reshape(3,3)
	print("The 3x3 matrix ranging from 2-10 :\n",matrix)

if __name__=="__main__":
  	main()

The 3x3 matrix ranging from 2-10 :
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


## 3. Write a Python program to create a null vector of size 10 and update sixth value to 11.  
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]  <br>
Update sixth value to 11  <br>
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.] 

In [5]:
def main():
	matrix = np.zeros(10,dtype=int)
	matrix[6-1]=11
	print(matrix)
	

if __name__=="__main__":
  	main()

[ 0  0  0  0  0 11  0  0  0  0]


	
## 4. Write a Python program to reverse an array (first element becomes last).
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]<br>
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [6]:
def reverse_array(arr):
	"""
    Description:
      This function reverse the given array
    Parameters:
      arr(array): Array of items/int

    Returns:
      array : Reverse the array 
    """	
	return np.flip(arr)

def main():
	arr = np.arange(11)
	print(f"Original Array: {arr}")
	print(f"Reverse array: {reverse_array(arr)}")
	

if __name__=="__main__":
  	main()

Original Array: [ 0  1  2  3  4  5  6  7  8  9 10]
Reverse array: [10  9  8  7  6  5  4  3  2  1  0]


## 5. Write a Python program to create a 2d array with 1 on the border and 0 inside.


Expected Output:
<br>
Original array:<br>
[[ 1. 1. 1. 1. 1.]<br>
[ 1. 1. 1. 1. 1.]<br>
[ 1. 1. 1. 1. 1.]<br>
[ 1. 1. 1. 1. 1.]<br>
[ 1. 1. 1. 1. 1.]]<br><br>
1 on the border and 0 inside in the array<br>
[[ 1. 1. 1. 1. 1.]<br>
[ 1. 0. 0. 0. 1.]<br>
[ 1. 0. 0. 0. 1.]<br>
[ 1. 0. 0. 0. 1.]<br>
[ 1. 1. 1. 1. 1.]]

In [7]:
def main():
	arr = np.ones((5,5))
	print("Original array : \n",arr)
	arr[1:-1,1:-1]=0
	print("\nModified array : \n",arr)
	

if __name__=="__main__":
  	main()

Original array : 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Modified array : 
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## 6. Write a Python program to add a border (filled with 0's) around an existing array.  
Expected Output: <br>
Original array:  <br>
[[ 1. 1. 1.]  <br>
[ 1. 1. 1.]  <br>
[ 1. 1. 1.]]  <br>
1 on the border and 0 inside in the array  <br><br>
[[ 0. 0. 0. 0. 0.]  <br>
[ 0. 1. 1. 1. 0.]  <br>
[ 0. 1. 1. 1. 0.]  <br>
[ 0. 1. 1. 1. 0.]  <br>
[ 0. 0. 0. 0. 0.]]

In [13]:
def main():
	arr = np.ones((3,3))
	print("Original array : \n",arr)
	arr = np.pad(arr,pad_width=1,mode='constant',constant_values=0)
	print("\nModified array : \n",arr)
	

if __name__=="__main__":
  	main()

Original array : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Modified array : 
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


## 7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.  
Checkerboard pattern: <br>
[[0 1 0 1 0 1 0 1]  <br>
[1 0 1 0 1 0 1 0]  <br>
[0 1 0 1 0 1 0 1]  <br>
[1 0 1 0 1 0 1 0]  <br>
[0 1 0 1 0 1 0 1]  <br>
[1 0 1 0 1 0 1 0]  <br>
[0 1 0 1 0 1 0 1]  <br>
[1 0 1 0 1 0 1 0]]

In [19]:
def main():
	matrix = np.zeros((8,8), dtype=int)
	matrix[::2, ::2] = 1  # Set the elements at even indices to 1
	matrix[1::2, 1::2] = 1  # Set the elements at odd indices to 1
	print(matrix)

if __name__=="__main__":
  main()

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


## 8. Write a Python program to convert a list and tuple into arrays.  
List to array: <br>
[1 2 3 4 5 6 7 8]  <br><br>
Tuple to array: <br>
[[8 4 6]  <br>
[1 2 3]]

In [30]:
def main():
	lst = [1, 2, 3, 4, 5, 6, 7, 8]
	tpl = ((8, 4, 6), (1, 2, 3))

	print("List to array:")
	print(np.array(lst))

	print("\nTuple to array:")
	print(np.array(tpl))
    
if __name__=="__main__":
  main()

List to array:
[1 2 3 4 5 6 7 8]

Tuple to array:
[[8 4 6]
 [1 2 3]]


## 9. Write a Python program to append values to the end of an array.  
Expected Output: <br>
Original array:<br> 
[10, 20, 30]  

In [33]:
def append_to_array(array, values):
  """
	Description:
    Append values to the end of a NumPy array.
    
  Parameters:
      array (np.ndarray): The original NumPy array.
      values (list or np.ndarray): Values to be appended.
    
  Returns:
      np.ndarray(array): The updated NumPy array with appended values.
    """
  return np.append(array, values)

def main():
  original_array = np.array([10, 20, 30])
  values_to_append = [40, 50, 60]

  updated_array = append_to_array(original_array, values_to_append)
    
  print("Original array:")
  print(original_array)
    
  print("\nArray after appending values:")
  print(updated_array)

if __name__ == "__main__":
  main()

Original array:
[10 20 30]

Array after appending values:
[10 20 30 40 50 60]
